apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloapp
  name: helloapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - image: mariamkasssab/iti_project:v${BUILD_NUMBER}
        name: helloapp
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources: {}
