apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
spec:
  ports:
  - name: helloport
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: helloapp
  type: LoadBalancer
status:
  loadBalancer: {}
